
## Abstract

<!-- 
The Abstract comes after the title page in the manuscript file. The abstract text is also entered in a separate field in the submission system.

The Abstract should:
  Describe the main objective(s) of the study
  Explain how the study was done, including any model organisms used, without methodological detail
  Summarize the most important results and their significance
  Not exceed 300 words
Abstracts should not include:
  Citations
  Abbreviations, if possible
-->

<!-- from intro: -->
<!-- Knowing where species exist and thrive is fundamental to the sciences of ecology, biogeography, and conservation.  This body of science has resulted in various compiled databases of species distribution and range maps which provide foundational information for understanding species diversity and extinction risk, predicting species responses to human impacts and climate change, and managing and protecting species effectively.  No species range dataset can claim to represent the "truth" of any species' spatial distribution, but rather each offers its own distinct understanding of that latent distribution.  These varying predictions of species presence and absence, driven by intent and methodology, can result in very different predictions of species presence; however, conservation managers and policy makers must base their actions on conclusions drawn from these imperfect datasets.  It is critical to understand the differences in spatial range datasets and the implications of these differences for conservation research and decision-making. -->
 
Species distribution data provide the foundation for a wide range of ecological research studies and conservation management decisions.  Two major efforts to provide marine species distributions at a global scale are the International Union for Conservation of Nature (IUCN), which provides expert-generated range maps that outline the complete extent of a species' distribution; and AquaMaps, which provides model-generated species distribution maps that predict areas occupied by the species.  Neither dataset claims to represent the "truth" of species' spatial distributions, but rather each communicates a distinct understanding of the underlying distribution, with a distinct purpose in mind.

Together these databases represent `r format(n_spp_all, big.mark = ',')` species (`r format(p_spp_am, big.mark = ',')`% within AquaMaps, `r format(p_spp_iucn, big.mark = ',')`% within IUCN), with only `r format(n_spp_both, big.mark = ',')` shared species.  Ideally, the decision to use one dataset one over the other should carefully consider the purpose for which it was designed, but this small overlap between the two suggests that data availability is likely an important factor as well.

Differences in intent and methodology can result in very different predictions of species distributions, which bear important implications for scientists and decision makers who rely upon these datasets to inform conservation policy and management actions.  Comparing distributions for the small subset of species with maps in both datasets, we highlight several differences resulting from differences in methodology and intent.  In particular, we find that IUCN maps greatly overpredict coral presence into unsuitably deep waters, and we demonstrate that AquaMaps methodology can produce odd discontinuities at the extremes of a species range.  We illustrate the scientific and management implications of these tradeoffs by repeating a global analysis of gaps in coverage of marine protected areas, and find significantly different results depending on how the two datasets are used.

It remains essential to recognizes the tradeoffs between these two valuable marine datasets, and understand the implications of these tradeoffs for conservation research and decision-making.
