
## Summary

<!--_Abstract. Provide an abstract of no more than 250 words on page 2 of the manuscript. Abstracts should explain to the general reader the major contributions of the article. References in the abstract must be cited in full within the abstract itself and cited in the text._-->

1. Species distribution data provide the foundation for a wide range of ecological research studies and conservation management decisions, yet most species ranges remain unknown, and existing range maps often suffer from data limitations and inconsistencies.  AquaMaps and the International Union for Conservation of Nature (IUCN) are two distinct efforts to map marine species distributions at a global scale.  Together these databases represent `r format(n_spp_all, big.mark = ',')` species (`r format(p_spp_am, big.mark = ',')`% within AquaMaps, `r format(p_spp_iucn, big.mark = ',')`% within IUCN), with only `r format(n_spp_both, big.mark = ',')` shared species.  
2. Here we examine differences in predicted species ranges between the two datasets by comparing alignment of distribution (predicted species range common to both datasets) and area (extent of range predicted by each dataset) to identify potential sources of misalignment.
3. We find that these misalignments mainly result from divergent methodologies that introduce differing frequencies of commission and omission errors. For example, species ranges predicted by IUCN range maps frequently overextend into unsuitably deep territory, as in the case of many coral and reef-associated species; similarly, the AquaMaps species distribution model often predicts species presence far afield from known occurrences when extrapolating based on limited observations.
4. __Policy implications:__ We illustrate the scientific and management implications of these differences by repeating two recent applications - an assessment of global biodiversity within the Ocean Health Index and a global analysis of gaps in coverage of marine protected areas - and find significantly different results depending on how the two datasets are used.  Until a single, highly accurate dataset of global marine species ranges becomes available, understanding the implications of dataset differences for conservation planning and decision-making remains essential.

