---
title: "Aligning species range data to better serve science and conservation"
author: "Casey O'Hara, Jamie Afflerbach, Ben Halpern"
output:
  html_document:
    highlight: haddock
    number_sections: yes
    theme: spacelab
    toc: yes
  pdf_document:
    number_sections: yes
    toc: no
  word_document: null
---

``` {r setup, echo = FALSE, message = FALSE, warning = FALSE}

# library(ggplot2)
# library(maps)
# library(readr)
# library(raster)
# library(data.table)
library(tidyr)
library(dplyr)
library(stringr)

# dir_N <- c('Windows' = '//neptune.nceas.ucsb.edu/data_edit',
#            'Darwin'  = '/Volumes/data_edit',
#            'Linux'   = '/var/data/ohi')[[ Sys.info()[['sysname']] ]]

# dir_anx <- file.path(dir_N, 'git-annex/globalprep/SPP_ICO')
# dir_data <- file.path(dir_N, 'git-annex/globalprep/_raw_data')
# dir_fig <- file.path(getwd(), 'figures')
```

``` {r load data, echo = FALSE, warning = FALSE, message = FALSE}
### use data_explore.Rmd to create this file, if it does not yet exist.

data_file <- 'data/spp_list_w_area_trimmed.csv'
spp_map_pairs <- read.csv(data_file, stringsAsFactors = FALSE) %>%
  filter(!is.na(popn_category)) %>% ### filter out unassessed species
  filter(!is.na(sm_perc))           ### filter out NA maps (usually IUCN maps with no polygons)

### generate other lists

spp_all_file <- 'data/spp_all_2015.csv'
spp_all <- read.csv(spp_all_file, stringsAsFactors = FALSE) 

iucn_marine_file <- 'data/spp_iucn_marine.csv'
spp_iucn_marine <- read.csv(iucn_marine_file, stringsAsFactors = FALSE) 

iucn_maps_file <- 'data/spp_iucn_maps.csv'
spp_iucn_maps <- read.csv(iucn_maps_file, stringsAsFactors = FALSE) %>%
  rename(sciname = binomial) %>%
  filter(spp_group != 'hagfishes') %>%           ### not from IUCN...
  filter(sciname %in% spp_iucn_marine$sciname)   ### ditch freshwater spp

spp_am_file <- 'data/spp_am.csv'
spp_am <- read.csv(spp_am_file, stringsAsFactors = FALSE)


```

-----

``` {r abstract, child = 'ms_1_abst_sig.Rmd'}
```

-----

``` {r abstract, child = 'ms_2_intro_res_disc.Rmd'}
```

-----

``` {r abstract, child = 'ms_3_methods.Rmd'}
```

-----

``` {r abstract, child = 'ms_4_figs.Rmd'}
```

-----

``` {r abstract, child = 'ms_5_refs.Rmd'}
```