---
title: 'Data Exploration: IUCN and AquaMaps'
output: html_document
---

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}

# Libraries and Paths

library(ggplot2)
library(maps)
library(readr)
library(data.table)
library(raster)
library(tidyr)
library(dplyr)
library(stringr)

dir_N <- c('Windows' = '//neptune.nceas.ucsb.edu/data_edit',
           'Darwin'  = '/Volumes/data_edit',
           'Linux'   = '/var/data/ohi')[[ Sys.info()[['sysname']] ]]

dir_git <- '~/github/IUCN-AquaMaps'
  
dir_anx <- file.path(dir_N, 'git-annex/globalprep/SPP_ICO')
dir_fig <- file.path(dir_git, 'figures')
dir_data <- file.path(dir_git, 'data')

if(basename(getwd()) != 'data_explore') setwd('data_explore')
source('data_explore_fxns.R')
### When knitting this, it automatically sets WD to be this directory...
### the 'setwd()' is there for running by chunk
```


```{r get_spp_list, echo = FALSE, warning = FALSE, message = FALSE, eval = TRUE}
### this file created in data_prep
spp_list <- read_csv(file.path(dir_data, 'spp_list_w_area_trimmed.csv'))

loiczid_raster_file  <- file.path(dir_git, 'shiny/data/loiczid_raster.grd')
loiczid_raster       <- raster::raster(loiczid_raster_file)
names(loiczid_raster) <- 'loiczid'

```


``` {r plot_spp_iucn_gaps_tenplus, eval = TRUE, echo = FALSE, warning = FALSE}

iucn_gap10     <- read_csv(file.path(dir_data, 'iucn_gaps_tenplus.csv'))
iucn_gap10_spp <- unique(iucn_gap10[iucn_gap10$iucn_sid %in% spp_list$iucn_sid, ])

iucn_gapmaps <- sample_n(iucn_gap10_spp %>% filter(cat == 'gap'), 10)
iucn_10maps  <- sample_n(iucn_gap10_spp %>% filter(cat != 'gap'), 10)

if(!exists('iucn_spp_cells')) {
  iucn_spp_cells <- read_csv(file.path(dir_anx, 'explore_am_v_iucn/iucn_spp_cells_2015.csv'),
                             col_types = 'cddddc')
  am_spp_cells   <- read_csv(file.path(dir_anx, 'explore_am_v_iucn/am_spp_cells_2015.csv'))
}

am_thresh = 0

message('Printing gap maps')
for (i in 1:nrow(iucn_gapmaps)) { ### i <- 1
  spp <- iucn_gapmaps[i, ]
  
  spp_plot <- plot_rangemap(spp)
  spp_plot <- spp_plot +
    labs(title = sprintf('%s: %s', spp$sciname, spp$spp_group))

  print(spp_plot)
}

message('Printing >10% maps')

for (i in 1:nrow(iucn_10maps)) { ### i <- 1
  spp <- iucn_10maps[i, ]
  spp_plot <- plot_rangemap(spp)
  spp_plot <- spp_plot +
    labs(title = sprintf('%s: %s', spp$sciname, spp$spp_group))

  print(spp_plot)
}

```

