---
title: 'Data Prep: IUCN and AquaMaps'
output: html_document
---

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}

# Libraries and Paths

library(raster)
library(readr)
library(data.table)
library(tidyr)
library(dplyr)
library(stringr)

dir_M <- c('Windows' = '//mazu.nceas.ucsb.edu/data_edit',
           'Darwin'  = '/Volumes/ohi',
           'Linux'   = '/home/shares/ohi')[[ Sys.info()[['sysname']] ]]

dir_git <- '~/github/IUCN-AquaMaps'
  
dir_anx <- file.path(dir_M, 'git-annex/globalprep/spp_ico')
dir_fig <- file.path(dir_git, 'figures')
dir_data <- file.path(dir_git, 'data')
dir_data_remote <- file.path(dir_M, 'git-annex/globalprep/_raw_data')
scenario <- 'v2016'

if(basename(getwd()) != 'data_explore') setwd('~/github/IUCN-AquaMaps/data_explore')
source('data_explore_fxns.R')
### When knitting this, it automatically sets WD to be this directory...
### the 'setwd()' is there for running by chunk
```


```{r verify_spp_names_in_shps, echo = FALSE, warning = FALSE, message = FALSE, eval = FALSE}
### Some species names in the shapefile polygons do not match the IUCN database names.  Fix this!

spp_iucn_maps <- read_csv(file.path(dir_data, 'spp_iucn_maps.csv'))

# x <- spp_iucn_maps %>%
#   filter(is.na(iucn_subpop) & !is.na(iucn_sid)) %>%
#   filter(! spp_group %in% c('REPTILES', 'SEASNAKES', 'MANGROVES', 'SEAGRASSES')) %>%
#   filter(sciname %in% .$sciname[duplicated(.$sciname)])
### 37 instances of duped scinames with different IDs

api_key <- scan(file.path(dir_anx, 'api_key.csv'), what = 'character')

spp_id_url <- 'http://apiv3.iucnredlist.org/api/v3/species/id/%s?token=%s'

sid_list <- spp_iucn_maps %>%
  filter(!is.na(iucn_sid)) %>% 
  .$iucn_sid %>%
  unique() %>%
  sort()
    
ptm <- proc.time()
spp_names_df <- mc_get_from_api(spp_id_url, sid_list, api_key, delay = 1, cores = 16) %>%
  select(iucn_sid = taxonid, sciname2 = scientific_name)
proc.time() - ptm

spp_iucn_maps1 <- spp_iucn_maps %>%
  left_join(spp_names_df, by = 'iucn_sid') %>% ### here, both the shapefile name and API name
  select(-sciname) %>%
  rename(sciname = sciname2) ### now just the API name by ID number

write_csv(spp_iucn_maps1, file.path(dir_data, 'spp_iucn_maps_verified.csv'))

```

``` {r test_worrms_matching}

library(worrms)
spp_map_pairs <- read_csv(file.path(dir_data, 'spp_list_w_area_trimmed.csv'))

spp_names <- spp_map_pairs$sciname

iucn_maps_file <- file.path(dir_data, 'spp_iucn_maps_verified.csv')
spp_iucn_maps <- read_csv(iucn_maps_file)

spp_am_maps <- read_csv(file.path(dir_data, 'speciesoccursum.csv')) %>%
  mutate(sciname = paste(str_trim(genus), str_trim(species)),
         iucn_id = as.integer(iucn_id)) %>%
  dplyr::select(am_sid = speciesid, sciname, reviewed, iucn_id)

spp_am_ver <- lapply(spp_am_maps$sciname, FUN = function(x) {
    y <- try(wm_records_names(x))
    if (class(y) != 'try-error') {
      return(as.data.frame(y))
    } else {
      return(data.frame(status = 'error'))
    }
  }) %>%
  setNames(spp_am_maps$sciname) %>%
  bind_rows(.id = 'sciname_orig')

spp_am_ver1 <- spp_am_maps %>%
  select(am_sid, sciname, iucn_id) %>%
  left_join(spp_am_ver %>%
    select(sciname_orig, sciname_worrms = scientificname, status, sciname_accepted = valid_name),
    by = c('sciname' = 'sciname_orig')) %>%
  distinct() %>%
  mutate(am_name_ver = sciname == sciname_accepted)

write_csv(spp_am_ver1, file.path(dir_git, 'data/sciname_lookups/am_worrms_verified.csv'))

spp_iucn_ver <- lapply(spp_iucn_maps$sciname, FUN = function(x) {
    y <- try(wm_records_names(x))
    if (class(y) != 'try-error') {
      return(as.data.frame(y))
    } else {
      return(data.frame(status = 'error'))
    }
  }) %>%
  setNames(spp_iucn_maps$sciname) %>%
  bind_rows(.id = 'sciname_orig')

spp_iucn_ver1 <- spp_iucn_maps %>%
  select(iucn_sid, sciname, spp_group) %>%
  left_join(spp_iucn_ver %>%
    select(sciname_orig, sciname_worrms = scientificname, status, sciname_accepted = valid_name),
    by = c('sciname' = 'sciname_orig')) %>%
  distinct() %>%
  mutate(iucn_name_ver = sciname == sciname_accepted)

write_csv(spp_iucn_ver1, file.path(dir_git, 'data/sciname_lookups/iucn_worrms_verified.csv'))


### match by id first
id_match <- inner_join(spp_iucn_ver1 %>%
                         select(iucn_sid, iucn_sciname = sciname, iucn_sciname_accepted = sciname_accepted), 
                       spp_am_ver1 %>%
                         select(am_sid, iucn_id, am_sciname = sciname, am_sciname_accepted = sciname_accepted),
                       by = c('iucn_sid' = 'iucn_id')) %>%
  distinct()
### 1960 matches; all distinct?
# length(id_match$iucn_sid %>% unique()); length(id_match$am_sid %>% unique())
# 1880 for both (same as prior method, which makes sense)

### then match the rest by verified accepted name
iucn_id_miss <- spp_iucn_ver1 %>%
  filter(!iucn_sid %in% id_match$iucn_sid)
am_id_miss <- spp_am_ver1 %>%
  filter(!am_sid %in% id_match$am_sid)

name_match_base <- inner_join(iucn_id_miss, am_id_miss, by = 'sciname')
# length(name_match_base$iucn_sid %>% unique()); length(name_match_base$am_sid %>% unique())
### additional 463; 452 are unique, for total of 2332, which matches old method
name_match_worms <- inner_join(iucn_id_miss %>%
                                 filter(!is.na(sciname_accepted)) %>%
                                 rename(iucn_sciname = sciname), 
                               am_id_miss %>%
                                 filter(!is.na(sciname_accepted)) %>%
                                 rename(am_sciname = sciname), 
                               by = 'sciname_accepted') %>%
  filter(status.x != 'unaccepted' & status.y != 'unaccepted') ### both unaccepted? too much uncertainty - eliminate

# length(name_match_worms$iucn_sid %>% unique()); length(name_match_worms$am_sid %>% unique())
### additional 480; 467 IUCN are unique, and 464 AquaMaps, for total of 2332, which makes sense
worms_no_basename <- name_match_worms %>%
  filter(!iucn_sid %in% name_match_base$iucn_sid) %>%
  select(iucn_sid, am_sid, sciname = sciname_accepted)
### matched by WoRMS names but not by basic names from original databases

basename_no_worms <- name_match_base %>%
  filter(!am_sid %in% name_match_worms$am_sid) %>%
  select(iucn_sid, am_sid, sciname)
### these are all ones with no WoRMS match for either database, but matched by original names

id_match_cleaned <- id_match %>%
  select(iucn_sid, am_sid, sciname = iucn_sciname) %>%
  distinct()

species_id_lookup <- id_match_cleaned %>%
  mutate(match = 'id') %>%
  bind_rows(name_match_base %>%
              select(iucn_sid, am_sid, sciname) %>%
              mutate(match = 'basic name')) %>%
  bind_rows(worms_no_basename %>%
              mutate(match = 'worms')) %>%
  distinct()

### 2351 species on the list
x <- species_id_lookup %>%
  filter(iucn_sid %in% species_id_lookup$iucn_sid[duplicated(species_id_lookup$iucn_sid)])
y <- species_id_lookup %>%
  filter(am_sid %in% species_id_lookup$am_sid[duplicated(species_id_lookup$am_sid)])

write_csv(species_id_lookup, file.path(dir_git, 'data/species_id_lookup.csv'))
# length(species_id_lookup$iucn_sid %>% unique()); length(species_id_lookup$am_sid %>% unique())
### 2335 iucn_sid, 2335 am_sid

```

```{r get_spp_all, echo = FALSE, warning = FALSE, message = FALSE, eval = FALSE}

spp_iucn_maps <- read_csv(file.path(dir_data, 'spp_iucn_maps_verified.csv'))

spp_am_maps <- read_csv(file.path(dir_data, 'speciesoccursum.csv')) %>%
  mutate(sciname = paste(str_trim(genus), str_trim(species)),
         iucn_id = as.integer(iucn_id)) %>%
  dplyr::select(am_sid = speciesid, sciname, reviewed, iucn_id)

spp_all <- spp_iucn_maps %>%
  filter(iucn_sid %in% spp_am_maps$iucn_id) %>%
  left_join(spp_am_maps %>% 
              rename(am_sciname = sciname) %>%
              mutate(iucn_sid = iucn_id), ### keep the IUCN noted ID separate from AM-noted IUCN id
            by = c('iucn_sid')) %>%
  bind_rows(x <- spp_iucn_maps %>%
              filter(!iucn_sid %in% spp_am_maps$iucn_id) %>%
              full_join(spp_am_maps %>%
                          mutate(am_sciname = sciname) %>%
                          filter(!iucn_id %in% spp_iucn_maps$iucn_sid | is.na(iucn_id)),
                        by = c('sciname'))) %>%
  distinct()

# x <- spp_all %>% 
#   filter(is.na(iucn_subpop) & !is.na(iucn_sid)) %>%
#   filter(iucn_sid %in% .$iucn_sid[duplicated(.$iucn_sid)])
### just seasnakes/reptiles and mangroves/seagrasses

# length(unique(spp_all$iucn_sid)) ###  4028, incl NA
# length(unique(spp_all$am_sid))   ### 22890, incl NA
# qwer <- spp_all %>% filter(!is.na(iucn_sid) & !is.na(am_sid))
# length(unique(qwer$iucn_sid)) ### 2343
# length(unique(qwer$am_sid)) ### 2337

# 
# x <- spp_iucn_maps %>%
#   rename(iucn_sciname = sciname) %>%
#   full_join(spp_am_maps %>%
#               rename(am_sciname = sciname),
#             by = c('iucn_sid' = 'iucn_id')) %>%
#   select(iucn_sid, iucn_sciname, am_sid, am_sciname) %>%
#   mutate(name_match = iucn_sciname == am_sciname) %>%
#   distinct()
# asdf <- x %>% filter(!is.na(iucn_sid) & !is.na(am_sid)) %>%
#   filter(!is.na(iucn_sciname) & !is.na(am_sciname))
# length(unique(asdf$iucn_sid)) # 1880
# length(unique(asdf$am_sid)) # 1880
### 1880 species matched if only using ID number...

write_csv(spp_all, file.path(dir_data, 'spp_all_maps.csv'))

```

```{r get_other_vars, echo = FALSE, warning = FALSE, message = FALSE, eval = FALSE}
### create spp_am_v_iucn: the whole maplist narrowed down to just the overlapping species.
### Overlaps detected from spatial_source containing 'iucn' (b/c source_pref = 'iucn' above),
### that also have a non-NA AquaMaps ID code.
spp_all <- read_csv(file.path(dir_data, 'spp_all_maps.csv'))

species_id_lookup <- read_csv(file.path(dir_git, 'data/species_id_lookup.csv'))

spp_am_v_iucn <- spp_all %>%
  select(-iucn_subpop) %>%
  filter(iucn_sid %in% species_id_lookup$iucn_sid & am_sid %in% species_id_lookup$am_sid) %>% #  & !is.na(am_sid)) %>%
  unique()

# length(unique(spp_am_v_iucn$sciname)); length(unique(spp_am_v_iucn$am_sid)); length(unique(spp_am_v_iucn$iucn_sid))
### NOTE: 23325 unique scientific names, unique am_sid and unique iucn_sid.
### Seasnakes are included in Reptiles (IUCN).  Two "mangroves" that are actually seagrasses.
spp_am_v_iucn <- spp_am_v_iucn %>%
  group_by(am_sid, iucn_sid) %>%
  mutate(dupes = n() - 1) %>%
  ungroup() %>%
  filter(!(dupes == 1 & spp_group == 'MANGROVES')) %>%
  filter(spp_group != 'SEASNAKES') %>%
  select(-dupes)
# length(unique(spp_am_v_iucn$sciname)); length(unique(spp_am_v_iucn$am_sid)); length(unique(spp_am_v_iucn$iucn_sid))
### still same scinames and am_sid

sciname_dupes <- spp_am_v_iucn %>%
  group_by(am_sid) %>%
  filter(n() > 1)
### these seem to be spp with IUCN maps for synonyms.  Keep 'em in.

write_csv(spp_am_v_iucn, file.path(dir_data, 'spp_am_v_iucn.csv'))

```

```{r read_am_and_iucn_data, echo = FALSE, warning = FALSE, message = FALSE}

# spp_am_v_iucn <- read_csv(file.path(dir_data, 'spp_am_v_iucn.csv'))

# Data files

# iucn_spp_cells_files <- list.files(file.path(dir_anx, 'vAM_IUCN/iucn_intersections'), full.names = TRUE)
# iucn_spp_cells_all <- lapply(iucn_spp_cells_files, FUN = function(x) {
#   read_csv(x) %>%
#     mutate(iucn_sid = as.integer(iucn_sid))
#   }) %>%
#   bind_rows() %>%
#   setNames(tolower(names(.)))
# 
# spp_iucn_maps1 <- read_csv(file.path(dir_data, 'spp_iucn_maps_verified.csv')) %>%
#   select(sciname, iucn_sid_ver = iucn_sid) %>%
#   distinct()

### because the 2015 shapefiles for reptiles and mammals were modified
### to attach subpop IDs rather than parent IDs to subpops, we will undo
### this here by overwriting the IDs based on parent IDs.
# iucn_spp_cells_verified <- iucn_spp_cells_all %>%
#   left_join(spp_iucn_maps1, by = 'sciname') %>%
#   mutate(iucn_sid = iucn_sid_ver)
# 
# iucn_spp_cells <- iucn_spp_cells_verified %>%
#   filter(iucn_sid %in% spp_am_v_iucn$iucn_sid) %>%
#   filter(presence != 5) %>%
#   select(-iucn_sid_ver)

## length(unique(iucn_spp_cells$iucn_sid)) #  2330 species found...
##   some species with no cells reported.
## spp_missing <- spp_am_v_iucn %>% filter(!iucn_sid %in% iucn_spp_cells$iucn_sid)
##   2 spp with no cells reported.  Shapefile errors?
# write_csv(iucn_spp_cells, file.path(dir_anx, 'vAM_IUCN/iucn_spp_cells_2015.csv'))
# 
# message('Loading AquaMaps species to cell table.  This might take a few minutes.')
# am_spp_cells_all <- fread(file.path(dir_data_remote, 'aquamaps/d2015/csv/hcaf_sp_native_trunc.csv'),
#                          showProgress = TRUE)
# am_spp_cells <- am_spp_cells_all %>%
#   rename(am_sid = speciesid, prob = probability) %>%
#   filter(am_sid %in% spp_am_v_iucn$am_sid)
# ### length(unique(am_spp_cells$am_sid)) # results in 2332 species found
# write_csv(am_spp_cells, file.path(dir_anx, 'vAM_IUCN/am_spp_cells_2015.csv'))

```

``` {r get_spp_list, echo = FALSE, warning = FALSE, message = FALSE, eval = TRUE}
### Create files for species list with area info, both a complete list and a trimmed list

loiczid_raster_file  <- file.path(dir_git, 'data/rasters/loiczid_raster.tif')
loiczid_raster       <- raster::raster(loiczid_raster_file)
names(loiczid_raster) <- 'loiczid'

data_file <- file.path(dir_data, 'spp_list_w_area_all.csv')
reload <- TRUE
if (!file.exists(data_file) | reload) {

  if(!exists('am_spp_cells'))
    am_spp_cells <- read_csv(file.path(dir_anx, 'vAM_IUCN/am_spp_cells_2015.csv'))
  if(!exists('iucn_spp_cells'))
    iucn_spp_cells <- read_csv(file.path(dir_anx, 'vAM_IUCN/iucn_spp_cells_2015.csv'))
  
  ### species info list - scinames, IUCN species ID, AM species ID, category etc
  spp_list_base <- read_csv(file.path(dir_data, 'spp_am_v_iucn.csv'))
  create_spp_list(spp_list_base, data_file, am_spp_cells, iucn_spp_cells, loiczid_raster)
  
}

spp_list <- read_csv(data_file) 
### At this point, spp_list zero-area IUCNs due to missing (?) polygons (maybe points?)

spp_list <- spp_list %>%
  mutate(sm_perc = ifelse(is.na(sm_perc), 0, sm_perc)) %>%
  filter(!area_iucn == 0)
  ### will ditch the ones with no IUCN area - formerly caused by DD species
  ### being filtered out.  Now, only 2 suffer this consequence.

### attach group name text field, and occurcells field
spp_list <- spp_list %>%
  left_join(x <- read_csv(file.path(dir_data, 'sciname_lookups/spp_groupnames.csv')),
            by = 'spp_group') %>%
  left_join(read_csv(file.path(dir_data_remote, 'aquamaps/d2015/csv/speciesoccursum.csv')) %>% 
              select(am_sid = speciesid, occurcells),
            by = 'am_sid')

# cat_score_df <- data.frame(popn_category  = c('LC', 'NT', 'VU', 'EN', 'CR', 'EX', 'DD', 'NE'),
#                            category_score = c( 0.0,  0.2,  0.4,  0.6,  0.8,  1.0,   NA,  NA))
# spp_list <- spp_list %>%
#   left_join(cat_score_df, by = 'popn_category')

write_csv(spp_list, file.path(dir_data, 'spp_list_w_area_trimmed.csv'))

```

``` {r counts_spp_all_observations, echo = FALSE}

spp_map_pairs <- read_csv(file.path(dir_data, 'spp_list_w_area_trimmed.csv'))

library(rgbif)

# system.time({
#   x <- occ_search(scientificName = spp_map_pairs$sciname, fields = 'minimal', limit = 1)
#   ### seems linear - 10 names ~ 2.5 sec, 100 names ~ 25 sec, 1000 names, ~250 sec
#   ### so 30000 names ~ 7500 sec or 2 hours
# })
# y <- sapply(x, function(x) x$meta$count) %>%
#   unlist()
# gbif_occur <- data.frame(sciname = names(y), gbif_occ = y)
# 
# gbif_occur <- spp_map_pairs %>%
#   select(iucn_sid, am_sid, sciname) %>%
#   left_join(gbif_occur,
#             by = 'sciname') %>%
#   left_join(read_csv(file.path(dir_data_remote, 'aquamaps/d2015/csv/speciesoccursum.csv')) %>%
#                        select(am_sid = speciesid, occurcells),
#                      by = 'am_sid')
# 
# # plot(gbif_occ ~ occurcells, data = gbif_occur)
# # print(summary(lm(obs ~ occurcells, data = gbif_occur)))
# 
# write_csv(gbif_occur, file.path(dir_data, 'gbif_occurrence.csv'))
# # gbif_occur <- read_csv(file.path(dir_data, 'gbif_occurrence.csv'))

# source('obis_count.R')
# scinames <- spp_map_pairs$sciname
# 
# obis_occur <- obis_count(scinames, verbose = TRUE)
# # obis_occur <- obis_count(scinames[1:10], verbose = TRUE)
# 
# obis_occur <- spp_map_pairs %>%
#   select(iucn_sid, am_sid, sciname) %>%
#   left_join(obis_occur,
#             by = 'sciname') %>%
#   left_join(read_csv(file.path(dir_data_remote, 'aquamaps/d2015/csv/speciesoccursum.csv')) %>%
#                        select(am_sid = speciesid, occurcells),
#                      by = 'am_sid')
# 
# write_csv(obis_occur, file.path(dir_data, 'obis_occurrence.csv'))
# # obis_occur <- read_csv(file.path(dir_data, 'obis_occurrence.csv'))

```

