---
title: 'Data Exploration: IUCN and AquaMaps'
output: html_document
---

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}

# Libraries and Paths

library(ggplot2)
library(readr)
library(raster)
library(rgdal)
library(tidyr)
library(dplyr)
library(stringr)

dir_M <- c('Windows' = '//mazu.nceas.ucsb.edu/ohi',
           'Darwin'  = '/Volumes/ohi',    ### connect (cmd-K) to smb://mazu/ohi
           'Linux'   = '/home/shares/ohi')[[ Sys.info()[['sysname']] ]]

dir_git <- '~/github/IUCN-AquaMaps'
  
dir_anx <- file.path(dir_M, 'git-annex/globalprep/spp_ico')
dir_fig <- file.path(dir_git, 'figures')
dir_data <- file.path(dir_git, 'data')

source('~/github/IUCN-AquaMaps/data_explore/data_explore_fxns.R')

```


```{r get_spp_cells, echo = FALSE, warning = FALSE, message = FALSE, eval = TRUE}


paired_maps_file <- file.path(dir_data, 'spp_list_w_area_trimmed.csv')

rgn_cells_file <- file.path(dir_git, 'case_study_ohi/rgn_cells.csv')
if(!file.exists(rgn_cells_file)) 
  file.copy(file.path(dir_anx, 'rgns', 'cellID_rgn_gcs.csv'), rgn_cells_file)

ohi_rgn_cells <- read_csv(rgn_cells_file, col_types = 'icdd_d')

spp_map_pairs <- read_csv(paired_maps_file) %>%
  filter(!is.na(popn_category)) %>% ### filter out unassessed species
  filter(!is.na(sm_perc))           ### filter out NA maps

### Load species cells; filter to those in paired maps and those in OHI regions
am_paired_cells <- read_csv(file.path(dir_anx, 'vAM_IUCN/am_spp_cells_2015.csv')) %>%
  filter(am_sid %in% spp_map_pairs$am_sid) %>%
  filter(loiczid %in% ohi_rgn_cells$loiczid)

iucn_paired_cells <- read_csv(file.path(dir_anx, 'vAM_IUCN/iucn_spp_cells_2015.csv'),
                           col_types = 'cddddc') %>%
  filter(presence != 5) %>%
  filter(iucn_sid %in% spp_map_pairs$iucn_sid) %>%
  filter(loiczid %in% ohi_rgn_cells$loiczid)

```

``` {r calc_ohi_iucn_paired_spp}

### bind IUCN loiczid dataframe to species risk category dataframe
iucn_paired_cells <- iucn_paired_cells %>%
  left_join(spp_map_pairs %>% select(iucn_sid, cat_score = category_score),
            by = 'iucn_sid')

### group by loiczid, then summarize to find means (and counts)
iucn_cell_sum <- iucn_paired_cells %>%
  filter(!is.na(cat_score)) %>%
  group_by(loiczid) %>%
  summarize(mean_cat = mean(cat_score),
            n_spp    = n())

write_csv(iucn_cell_sum, file.path(dir_git, 'case_study_ohi/iucn_paired_cell_sum.csv'))

### bind cells to regions dataframe and summarize
iucn_rgn_sums <- iucn_cell_sum %>%
  inner_join(ohi_rgn_cells,
             by = 'loiczid') %>%
  # mutate(rgn_area = cell_area * proportionArea,
  #        area_weighted_mean_cat   = weighted_mean_cat   * rgn_area,
  #        area_weighted_mean_trend = weighted_mean_trend * rgn_area) %>%
  mutate(cell_area_weight = cell_area * n_spp * proportionArea,
         area_weighted_mean_cat = mean_cat * cell_area_weight) %>%
  arrange(loiczid)

iucn_rgn_sums <- iucn_rgn_sums %>%
  group_by(rgn_id) %>%
  summarize(rgn_mean_cat = sum(area_weighted_mean_cat)/sum(cell_area_weight))

iucn_rgn_sums <- iucn_rgn_sums %>%
  mutate(status = 100 * ((1 - rgn_mean_cat) - 0.25) / 0.75)

write_csv(iucn_rgn_sums, file.path(dir_git, 'case_study_ohi/iucn_paired_region_sums.csv'))

```

``` {r calc_ohi_am_paired_spp_0_thresh}

### bind IUCN loiczid dataframe to species risk category dataframe
am_paired_cells_0 <- am_paired_cells %>%
  left_join(spp_map_pairs %>% select(am_sid, cat_score = category_score),
            by = 'am_sid')

### group by loiczid, then summarize to find means (and counts)
am_cell_sum_0 <- am_paired_cells_0 %>%
  filter(!is.na(cat_score)) %>%
  group_by(loiczid) %>%
  summarize(mean_cat = mean(cat_score),
            n_spp    = n())

write_csv(am_cell_sum_0, file.path(dir_git, 'case_study_ohi/am_paired_cell_sum_0.csv'))

### bind cells to regions dataframe and summarize
am_rgn_sums_0 <- am_cell_sum_0 %>%
  inner_join(ohi_rgn_cells,
             by = 'loiczid') %>%
  # mutate(rgn_area = cell_area * proportionArea,
  #        area_weighted_mean_cat   = weighted_mean_cat   * rgn_area,
  #        area_weighted_mean_trend = weighted_mean_trend * rgn_area) %>%
  mutate(cell_area_weight = cell_area * n_spp * proportionArea,
         area_weighted_mean_cat = mean_cat   * cell_area_weight) %>%
  arrange(loiczid)

am_rgn_sums_0 <- am_rgn_sums_0 %>%
  group_by(rgn_id) %>%
  summarize(rgn_mean_cat = sum(area_weighted_mean_cat)/sum(cell_area_weight))

am_rgn_sums_0 <- am_rgn_sums_0 %>%
  mutate(status = 100 * ((1 - rgn_mean_cat) - 0.25) / 0.75)

write_csv(am_rgn_sums_0, file.path(dir_git, 'case_study_ohi/am_paired_region_sums_0.csv'))

```

``` {r calc_ohi_am_paired_spp40_thresh}

### bind IUCN loiczid dataframe to species risk category dataframe
am_paired_cells40 <- am_paired_cells %>%
  filter(prob >= 0.40) %>%
  left_join(spp_map_pairs %>% select(am_sid, cat_score = category_score),
            by = 'am_sid')

### group by loiczid, then summarize to find means (and counts)
am_cell_sum40 <- am_paired_cells40 %>%
  filter(!is.na(cat_score)) %>%
  group_by(loiczid) %>%
  summarize(mean_cat = mean(cat_score),
            n_spp    = n())

write_csv(am_cell_sum40, file.path(dir_git, 'case_study_ohi/am_paired_cell_sum40.csv'))

### bind cells to regions dataframe and summarize
am_rgn_sums40 <- am_cell_sum40 %>%
  inner_join(ohi_rgn_cells,
             by = 'loiczid') %>%
  # mutate(rgn_area = cell_area * proportionArea,
  #        area_weighted_mean_cat   = weighted_mean_cat   * rgn_area,
  #        area_weighted_mean_trend = weighted_mean_trend * rgn_area) %>%
  mutate(cell_area_weight = cell_area * n_spp * proportionArea,
         area_weighted_mean_cat = mean_cat   * cell_area_weight) %>%
  arrange(loiczid)

am_rgn_sums40 <- am_rgn_sums40 %>%
  group_by(rgn_id) %>%
  summarize(rgn_mean_cat = sum(area_weighted_mean_cat)/sum(cell_area_weight))

am_rgn_sums40 <- am_rgn_sums40 %>%
  mutate(status = 100 * ((1 - rgn_mean_cat) - 0.25) / 0.75)

write_csv(am_rgn_sums40, file.path(dir_git, 'case_study_ohi/am_paired_region_sums40.csv'))

```

``` {r create_violin_plots}
dir_fig <- '~/github/IUCN-AquaMaps/figures'
source(file.path(dir_git, 'data_explore/data_explore_fxns.R'))

iucn_rgn_sums  <- read_csv(file.path(dir_git, 'case_study_ohi/iucn_paired_region_sums.csv'))
am_rgn_sums_0  <- read_csv(file.path(dir_git, 'case_study_ohi/am_paired_region_sums_0.csv'))
am_rgn_sums40 <- read_csv(file.path(dir_git, 'case_study_ohi/am_paired_region_sums40.csv'))

status_df <- iucn_rgn_sums %>%
  select(rgn_id, iucn_st = status) %>%
  full_join(am_rgn_sums_0 %>% select(rgn_id, am_st_0 = status), by = 'rgn_id') %>%
  full_join(am_rgn_sums40 %>% select(rgn_id, am_st40 = status), by = 'rgn_id') %>%
  mutate(diff_am_0 = am_st_0 - iucn_st,
         diff_am40 = am_st40 - iucn_st,
         diff_am40_am0 = am_st_0 - am_st40) %>%
  gather(scenario, diff, diff_am_0:diff_am40_am0) %>%
  mutate(scenario = factor(scenario, levels = c('diff_am40', 'diff_am_0', 'diff_am40_am0')))
  
bplot_abs <- ggplot(data = status_df, aes(x = scenario, y = diff)) +
  ggtheme_plot + 
  theme(panel.grid.major = element_line(colour = 'grey90', size = .25),
        panel.grid.major.x = element_blank()) +

  geom_hline(yintercept = 0, color = 'gray50', size = .5) +
  geom_violin(fill = 'grey80', alpha = .5,
              scale = 'width',
              draw_quantiles = c(.25, .5, .75)) +
  geom_point(position = position_jitter(w = .3), 
             color = 'black', alpha = 1, size = 0.25) +
  geom_violin(fill = NA, 
              draw_quantiles = c(.25, .5, .75),
              scale = 'width') +
  labs(x = 'Scenario',
       y = 'Change in SPP status') +
  scale_x_discrete(labels = c('1. AquaMaps \n(40% threshold)', 
                              '2. AquaMaps \n(no threshold)', 
                              '3. AquaMaps \n(40% -> no threshold)'))

print(bplot_abs)
ggsave(file.path(dir_fig, 'fig3a_violinplot_paired_maps.png'),
       height = 4.5, width = 8.7, units = 'cm', dpi = 600)
ggsave(file.path(dir_fig, 'fig3a_violinplot_paired_maps.tif'), device = 'tiff',
       height = 4.5, width = 8.7, units = 'cm', dpi = 600)

```
